### ISSUE TITLE
Uppräkning av premier

### ISSUE THREAD

**Issue by adamjohansson** [equipe/equipe_issues#117]
När det är mer än 100 starter ska man under premiekalkylatorn kunna räkna upp dem till först 33% och sedan 66% från 110-120 starter.

**Comment by adamjohansson** [comment]
Maximum 100 starters per Competition other than the GP. If more than 100 starters are declared, the OC must provide the following percentages of additional prize money for every ten
declared starters, up to 120 declared starters:
- 101 to 110 declared starters: 133% of the original Competition prize money must be provided;
- 111 to 120 declared starters: 166% of the original Competition prize money must be provided;
If more than 120 starters are declared, the OC must split the Competition and provide the equivalent amount of prize money for the additional Competition. OCs may apply either of the
following methods for splitting the Competition:
The competition is split into two groups before it starts. There may be a different number of starters in each group. There may be athletes with multiple horses in each group but all
horses of any one athlete must be in the same group.
or
The competition is run as one single competition and split afterward into two groups and the classification established as follows: the athlete with the best score is the winner of the
first group, the athlete with the second best score is the winner of the second group and so on until prizes have been allocated to 25% of the total number of starters. NB: In this case
separate results must be sent to the FEI for each of the two groups, e.g. results for Competition 1a and for Competition 1b.
In both cases above each group must offer the same amount of prize money as indicated for the original Competition. For the avoidance of doubt, it is the number of declared starters
in the Competition, not the final number of starters, that determines whether the Competition must be split.
If there are more than 240 declared starters, the OC must split the Competition into as many groups as and apply the same percentages of additional prize money as indicated above.

**Comment by jnstq** [comment]
Detta kommer ändras nästa år, så det är inte lönt att göra

**Comment by jnstq** [comment]
Den här är tydligen framflyttad, kommer vara samma nästa år.
