### ISSUE TITLE
Skriva ut generalprotokoll terräng

### ISSUE THREAD

**Issue by frofrik** [equipe/equipe_issues#18]
Generalprotokoll för alla hinder i terrängen.

**Comment by jnstq** [comment]
<img width="809" alt="cac58aca-33ae-11e6-8fa7-dab305a0fd37" src="https://user-images.githubusercontent.com/20176/63346894-409ac780-c356-11e9-951d-794b92490ead.png">

**Comment by jnstq** [comment]
<img width="1265" alt="Screenshot 2019-08-20 at 15 00 31" src="https://user-images.githubusercontent.com/20176/63349260-519a0780-c35b-11e9-824f-2c215016b1e4.png">
