### ISSUE TITLE
Sätt prispengar på lag vid import från FEI

### ISSUE THREAD

**Issue by frofrik** [equipe/equipe_issues#2]
När en lagklass importeras från FEI, sätt prispengarna på laget, ej individuellt.

**Comment by jnstq** [comment]
Denna borde redan vara fixad

**Comment by jnstq** [comment]
@frofrik fick du manuellt ändra detta på din tävling? Jag tror att jag ordna det innan sentower, efter Frankrike.

**Comment by frofrik** [comment]
Japp, jag ändrade manuellt


Vänliga hälsningar / Best Regards
Fredrik Starck



Tel: +46 (0)73 738 67 47
www.starckenterprises.com <http://www.starckenterprises.com/>

**Comment by jnstq** [comment]
Jag tror inte vi får den här infon från FEI, om du hittar en lagklass hos FEI som har prispengar så lägger vi till det.
