### ISSUE TITLE
Importera betalningar via CSV

### ISSUE THREAD

**Issue by frofrik** [equipe/equipe_issues#20]
Kunna ta med betalningar i CSV-importen vid import av t.ex. nationella tävlingar.

**Comment by jnstq** [comment]
Detta är fixat nu.

<img width="1490" alt="screen shot 2017-05-08 at 11 59 20" src="https://cloud.githubusercontent.com/assets/20176/25799584/cc61eb3e-33e5-11e7-9806-2af43d0f5722.png">
