### ISSUE TITLE
Skriva ut Masterlist 

### ISSUE THREAD

**Issue by kimfors** [equipe/equipe_issues#27]
kunna skriva ut en översikts masterlist med alla olika masterlists med gruppering

**Comment by jnstq** [comment]
Om du skriver ut en hästförteckning och kryssa för att listor ska komma med?

**Comment by jnstq** [comment]
Denna är för vag, behöver förstå vad som menas, det går att skriva ut en hästförteckning och välja att listor ska synas.

**Comment by kimfors** [comment]
http://jumping-chateauversailles.com/pdf/csi1_jumping-du-chateau-de-versailles_master-nations.pdf 

Något som denna 
Men tänker att vår kunde varit snyggare 
Men för att förstå upplägget

**Comment by jnstq** [comment]
Den här är väl inte helt orimlig att göra, det är en hästförteckning grupperad på land och ryttare, vi gjorde nyligen stöd för gruppera ryttarförteckningen på klubb.

**Comment by jnstq** [comment]
Vi borde också ha stöd för loggor på ryttar, häst och klubbförteckning

**Comment by kimfors** [comment]
Och möjlighet att få med vilken masterlist de är med på

**Comment by jnstq** [comment]
Det står ju bara i rubriken på ditt exempel, ser ut att vara CSI1 och ingen mix

**Comment by jnstq** [comment]
Men ska jag vara ärlig - när används en sådan här lista?
