### ISSUE TITLE
Gör det svårare att trycka Nollställ i domarinmatningen

### ISSUE THREAD

**Issue by frofrik** [equipe/equipe_issues#33]
Knappen för att Nollställa bör göras mindre eller tas bort helt i domarinmatningen.
Alldeles för enkelt att råka trycka där istället för godkänn. 
Jag har heller aldrig varit med om att man skulle vilja nollställa helt, då får man göra det från vanliga resultatinmatningen instället.

**Comment by jnstq** [comment]
Domare C bör fortfarande kunna göra allt, dvs strycka, utesluta osv för mindre tävlingar när man man inte är så aktiv i den övergripande resultatinmatningen
