### ISSUE TITLE
Fyraårsprotokoll hoppning

### ISSUE THREAD

**Issue by frofrik** [equipe/equipe_issues#46]
Kunna skriva ut fyraårsprotokoll i hoppningen.

[protokoll.pdf](https://github.com/equipe/equipe_issues/files/1287887/protokoll.pdf)

**Comment by jnstq** [comment]
Detta borde läggas in som ett dressyrprotokoll, det har varit så roligt att göra kombinationen av protokoll + tidtagning. Jag har tänkt på det ett tag. Vi borde ha det till swedehorse.

**Comment by jnstq** [comment]
Fixat med https://app.equipe.com/federations/20/marking_sheets/10988/edit
