### ISSUE TITLE
Sätt alltid avdelning A om B ej finns när man kopierar starter

### ISSUE THREAD

**Issue by frofrik** [equipe/equipe_issues#48]
Om man kopierar en start till en klass som var i avdelning B från början, men där den nya klassen enbart har avdelning A, så bör den starten ändras till avd. A.

**Comment by jnstq** [comment]
Det gör den, kopierar man till en klass som inte har unghästavdelning gör den om den till avd A.

Det finns två undantag, när man flyttar eller klassen är tom, då kör den inte logiken för "insert"

**Comment by jnstq** [comment]
Jag ändrar så den alltid sätter rätt unghästavdelning på en start man kopierar/flyttar/byter
