### ISSUE TITLE
Fördela inte starttider till strukna sist i en kategori

### ISSUE THREAD

**Issue by frofrik** [equipe/equipe_issues#56]
När man har ponnydressyr och lägger strukna sist så hamnar dom ju bara sist i respektive kategori, detta gör att dessa ekipage får starttider. Antingen om man kan göra så att alla strykningar hamnar sist efter alla kategorier, eller att fördelning av starttider hoppar över dessa.

**Comment by jnstq** [comment]
Ja, det bara handlar om att kolla kategorier så är detta möjligt att göra, värre om den också ska ta hänsyn till kategorisammanslagningen, och det borde den göra.

**Comment by jnstq** [comment]
Frågan är ju om den verkligen behöver ta hänsyn till kategorisammanslagning eller inte

**Comment by frofrik** [comment]
Starttiderna ska väl fördelas löpande oavsett?

**Comment by jnstq** [comment]
Jo men om kategorierna är blandade pga av kategorisammanställningen räcker det inte bara att jämför kategori

**Comment by jnstq** [comment]
Nu går den per kategori om grenen kräver att kategorier ska gå i ordning, annars går den bara från slutet som vanligt. Avdelning A och B är alltid uppdelat
