### ISSUE TITLE
Publicera inte D,H som ny startlista online

### ISSUE THREAD

**Issue by frofrik** [equipe/equipe_issues#64]
Om man har en startlista med bara hästar som är publicerad online, där det sen tillkommer en ponny, och publicerar på nytt, så publiceras det som en ny avdelning online. Står som t.ex. "D, H".

I app slås det ju samman, så det är bara på online det blir konstigt eftersom man får två listor helt plötsligt.

**Comment by jnstq** [comment]
Ja, om det är en hästklass, så borde den alltid gå till online.equipe.com som kategori häst oavsett vad som finns i den.

**Comment by jnstq** [comment]
Fixat med https://github.com/equipe/equipe_app/commit/356e820c4c2a6bad65bc7e819ea3d8cbe751a491
