### ISSUE TITLE
Varna om assessment-domare inte sitter på C

### ISSUE THREAD

**Issue by frofrik** [equipe/equipe_issues#68]
Om man anger domarna på annan position än C vid assessment så går det inte att skriva ut protokoll, men man får heller inget felmeddelande.

**Comment by jnstq** [comment]
Formuläret skulle börja helt tomt, och så lägger man till positionerna man vill använda, den första måste vara domare C. Då löser man detta utan validering.

**Comment by jnstq** [comment]
Vad tror du om det?

**Comment by frofrik** [comment]
Ja det hade varit en lösning
