### ISSUE TITLE
Quick-start for declaration

### ISSUE THREAD

**Issue by adamjohansson** [equipe/equipe_issues#71]
Kunna ställa in ipad-declaration via en QR-kod.

**Comment by jnstq** [comment]
Denna känner jag igen, vad har den för ursprung?

**Comment by hampus-n** [comment]
namnet? iOS 11, när man skannade gamla telefonen för att komma igång med den nya

**Comment by adamjohansson** [comment]
Vi pratade även om det på strategikonferensen, hade varit trevligt att kunna använda det på Friends.

**Comment by jnstq** [comment]
Förloppet är att ha en iPad med iOS11, tar fram kamera appen skannar en sida i app-equipe, och boom, man är inne. Jag gillar detta, blir extremt smidigt.
