### ISSUE TITLE
Officials in competitions

### ISSUE THREAD

**Issue by adamjohansson** [equipe/equipe_issues#84]
- Flags in ground jury, show directors etc
- Possibillity to add more than one Course Designer
- Simplified handling of officals; Set Type and Person
- Ground jury: President, Member, Foreign judge, Technical delegate, Course designer, Course designer assistant, Announcer, Show director, Press manager

**Comment by jnstq** [comment]
https://github.com/equipe/equipe_app/commit/a5173aaee0fa0347a23902f862f44977e3b7d477
