### ISSUE TITLE
Add support for label printer

### ISSUE THREAD

**Issue by adamjohansson** [equipe/equipe_issues#91]
Have the possibillity to print the horse labels (with the number to stick in the horse passports) directly from Competitions tab and with a label printer.
https://www.amazon.es/Brother-QL-700-Etiquetadora-negro-blanco/dp/B006LGYTH2/ref=sr_1_2?ie=UTF8&qid=1504207302&sr=8-2&keywords=impresora+etiquetas

**Comment by jnstq** [comment]
Just ordered a Brother-QL-700

**Comment by alancin** [comment]
Task finished!!! It's working good... Maybe is better when select the Stiker button, get all the horses pre selected and just unselect what do you don't want to print... Because is more normal to print all rider's passports labels in one time...
